//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhymarcyAppK204.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhymarcyDBEntities : DbContext
    {
        public PhymarcyDBEntities()
            : base("name=PhymarcyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Medicine_To_Firms> Medicine_To_Firms { get; set; }
        public virtual DbSet<Medicines_To_Tags> Medicines_To_Tags { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
